# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: development
      POSTGRES_DB: fusepong
    volumes:
        - ./db-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
